services:  
  db: 
    ports: 
      - ${PSQL_PORT}:5432 

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula 
    ports:
      - 3333:8080
  
  tailwind:
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./tailwind:/src
      - ./assets:/dst
      - ./templates:/templates